[project]
name = "cs3540-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "scikit-learn>=1.8.0",
]

[tool.pyright]
venvPath='.'
venv=".venv"
exclude=['.venv']
